[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
project_x_program = "8uGQrehARt9knb4Fs7j15tTVifLwvM56Lre53kYNurTy"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
